apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      targetPort: 6379
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "redis.name" . }}
    release: "{{ .Release.Name }}"

