image:
  repository: hub.i-soft.com.cn:5080/lxapp/owncloud
  tag: v1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi

