image:
  repository: hub.i-soft.com.cn:5080/lxapp/owncloud
  tag: v1.5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  storageClass: "vol1"
  accessMode: ReadWriteOnce
  size: 8Gi

