apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "httpd.fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "httpd.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: httpd
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html/
          name: data
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "httpd.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
