kind: Service
apiVersion: v1
metadata:
  name: {{ template "httpd.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "httpd.name" . }}
    release: "{{ .Release.Name }}"

