apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "owncloud.fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "owncloud.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: owncloud
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
          - containerPort: 80
          volumeMounts:
          - name: data
            mountPath: /var/www/owncloud
          volumes:
          - name: data
      {{- if .Values.persistence.enabled }}
            persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "owncloud.fullname" .) }}
      {{- else }}
            emptyDir: {}
      {{- end -}}


