apiVersion: v1
kind: Service
metadata:
  name: {{ template "owncloud.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "owncloud.name" . }}
    release: "{{ .Release.Name }}"

