apiVersion: v1
kind: Service
metadata:
  name: {{ template "memcache.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 11211
      targetPort: 11211
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "memcache.name" . }}
    release: "{{ .Release.Name }}"

